### PR TITLE
Recommendations migrated to link callouts

### PR DESCRIPTION
**Pull request by hero101**
- Requires an authorization reset to view the new callouts through the API

### CODE REVIEW

**Comment by hero101** [comment]
@valentinyanakiev Please review

**Review by valentinyanakiev — CHANGES_REQUESTED** [review]
Migration needs to be altered to accommodate storageBuckets. The column count changed with the previous migration, hence the following error:

```
query failed: 
    INSERT INTO profile VALUES
    ('e180cf82-2983-4ff5-b221-0ede7efef05a', NOW(), NOW(), 1, NULL, 'b21573b1-8633-4977-9fd9-1d1b0d32bce4', '17028005-1898-4451-8e10-1d19f7369b8e', NULL, NULL)
  
error: Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
    at /home/valentin/source/repos/alkemio/server/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:194:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sqlMessage: "Column count doesn't match value count at row 1",
  sqlState: '21S01',
  index: 0,
  sql: '\n' +
    '    INSERT INTO profile VALUES\n' +
    "    ('e180cf82-2983-4ff5-b221-0ede7efef05a', NOW(), NOW(), 1, NULL, 'b21573b1-8633-4977-9fd9-1d1b0d32bce4', '17028005-1898-4451-8e10-1d19f7369b8e', NULL, NULL)\n" +
    '  '
}
Migration "recommendationsToLinkCollection1682490418949" failed, error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
query: ROLLBACK
Error during migration run:
QueryFailedError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28) {
  query: '\n' +
    '    INSERT INTO profile VALUES\n' +
    "    ('e180cf82-2983-4ff5-b221-0ede7efef05a', NOW(), NOW(), 1, NULL, 'b21573b1-8633-4977-9fd9-1d1b0d32bce4', '17028005-1898-4451-8e10-1d19f7369b8e', NULL, NULL)\n" +
    '  ',
  parameters: undefined,
  driverError: Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
      at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      --------------------
      at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
      at /home/valentin/source/repos/alkemio/server/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:194:36
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
    errno: 1136,
    sqlMessage: "Column count doesn't match value count at row 1",
    sqlState: '21S01',
    index: 0,
    sql: '\n' +
      '    INSERT INTO profile VALUES\n' +
      "    ('e180cf82-2983-4ff5-b221-0ede7efef05a', NOW(), NOW(), 1, NULL, 'b21573b1-8633-4977-9fd9-1d1b0d32bce4', '17028005-1898-4451-8e10-1d19f7369b8e', NULL, NULL)\n" +
      '  '
  },
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sqlMessage: "Column count doesn't match value count at row 1",
  sqlState: '21S01',
  index: 0,
  sql: '\n' +
    '    INSERT INTO profile VALUES\n' +
    "    ('e180cf82-2983-4ff5-b221-0ede7efef05a', NOW(), NOW(), 1, NULL, 'b21573b1-8633-4977-9fd9-1d1b0d32bce4', '17028005-1898-4451-8e10-1d19f7369b8e', NULL, NULL)\n" +
```

**Review by valentinyanakiev — CHANGES_REQUESTED** [review]
```gql
query hub {
  hub(ID:"digicampus") {
    context
    {
      recommendations
      {
        description
      }
    }
  }
}
```

```{
  "errors": [
    {
      "message": "ER_BAD_FIELD_ERROR: Unknown column 'Context__Context_recommendations.contextRecommendationId' in 'field list'",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "hub",
        "context",
        "recommendations"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "SELECT DISTINCT `distinctAlias`.`Context_id` AS `ids_Context_id` FROM (SELECT `Context`.`id` AS `Context_id`, `Context`.`createdDate` AS `Context_createdDate`, `Context`.`updatedDate` AS `Context_updatedDate`, `Context`.`version` AS `Context_version`, `Context`.`vision` AS `Context_vision`, `Context`.`impact` AS `Context_impact`, `Context`.`who` AS `Context_who`, `Context`.`authorizationId` AS `Context_authorizationId`, `Context`.`ecosystemModelId` AS `Context_ecosystemModelId`, `Context__Context_recommendations`.`id` AS `Context__Context_recommendations_id`, `Context__Context_recommendations`.`createdDate` AS `Context__Context_recommendations_createdDate`, `Context__Context_recommendations`.`updatedDate` AS `Context__Context_recommendations_updatedDate`, `Context__Context_recommendations`.`version` AS `Context__Context_recommendations_version`, `Context__Context_recommendations`.`name` AS `Context__Context_recommendations_name`, `Context__Context_recommendations`.`uri` AS `Context__Context_recommendations_uri`, `Context__Context_recommendations`.`description` AS `Context__Context_recommendations_description`, `Context__Context_recommendations`.`authorizationId` AS `Context__Context_recommendations_authorizationId`, `Context__Context_recommendations`.`contextRecommendationId` AS `Context__Context_recommendations_contextRecommendationId`, `Context__Context_recommendations`.`profileId` AS `Context__Context_recommendations_profileId`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`id` AS `ccb636808c912b7629305069fc3f8c7098a495b36a1c81db8c8b2c88292c06f`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`createdDate` AS `b25a37f868987db7bd5ee9e3a85a589f24ed481ef542a85805c7f0b68bf4f31`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`updatedDate` AS `fa645b49577b7e49f536b89e2483f76e56bd96161e4571639cb11b83d1bb292`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`version` AS `8d89a8874cac95d57cb1f33efbdc40699af093ffdb42f45c1c782a2d4fb90f2`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`credentialRules` AS `122173152242f5bfd7208dfe4fde4db5794d32b1aeb2aa46067fb9f8d01b443`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`privilegeRules` AS `802adeafc30070c6fbefb52e8c209b8545087a7a9e15c4157c0a82ffa6d8438`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`verifiedCredentialRules` AS `4e37c61f9313ff2e70897581b17cc7b9d4771cb1c63d337f9b8cbc75acdec12`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`anonymousReadAccess` AS `9e3308ce00e54d7d61203719fce85ee7b74d66af83778162218471cf6e9ceb3`, `Context_authorization`.`id` AS `Context_authorization_id`, `Context_authorization`.`createdDate` AS `Context_authorization_createdDate`, `Context_authorization`.`updatedDate` AS `Context_authorization_updatedDate`, `Context_authorization`.`version` AS `Context_authorization_version`, `Context_authorization`.`credentialRules` AS `Context_authorization_credentialRules`, `Context_authorization`.`privilegeRules` AS `Context_authorization_privilegeRules`, `Context_authorization`.`verifiedCredentialRules` AS `Context_authorization_verifiedCredentialRules`, `Context_authorization`.`anonymousReadAccess` AS `Context_authorization_anonymousReadAccess` FROM `context` `Context` LEFT JOIN `reference` `Context__Context_recommendations` ON `Context__Context_recommendations`.`contextRecommendationId`=`Context`.`id`  LEFT JOIN `authorization_policy` `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea` ON `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`id`=`Context__Context_recommendations`.`authorizationId`  LEFT JOIN `authorization_policy` `Context_authorization` ON `Context_authorization`.`id`=`Context`.`authorizationId` WHERE (`Context`.`id` = ?)) `distinctAlias` ORDER BY `Context_id` ASC LIMIT 1",
          "parameters": [
            "03a66953-de0a-47c4-8c29-ded61da53487"
          ],
          "driverError": {
            "code": "ER_BAD_FIELD_ERROR",
            "errno": 1054,
            "sqlMessage": "Unknown column 'Context__Context_recommendations.contextRecommendationId' in 'field list'",
            "sqlState": "42S22",
            "index": 0,
            "sql": "SELECT DISTINCT `distinctAlias`.`Context_id` AS `ids_Context_id` FROM (SELECT `Context`.`id` AS `Context_id`, `Context`.`createdDate` AS `Context_createdDate`, `Context`.`updatedDate` AS `Context_updatedDate`, `Context`.`version` AS `Context_version`, `Context`.`vision` AS `Context_vision`, `Context`.`impact` AS `Context_impact`, `Context`.`who` AS `Context_who`, `Context`.`authorizationId` AS `Context_authorizationId`, `Context`.`ecosystemModelId` AS `Context_ecosystemModelId`, `Context__Context_recommendations`.`id` AS `Context__Context_recommendations_id`, `Context__Context_recommendations`.`createdDate` AS `Context__Context_recommendations_createdDate`, `Context__Context_recommendations`.`updatedDate` AS `Context__Context_recommendations_updatedDate`, `Context__Context_recommendations`.`version` AS `Context__Context_recommendations_version`, `Context__Context_recommendations`.`name` AS `Context__Context_recommendations_name`, `Context__Context_recommendations`.`uri` AS `Context__Context_recommendations_uri`, `Context__Context_recommendations`.`description` AS `Context__Context_recommendations_description`, `Context__Context_recommendations`.`authorizationId` AS `Context__Context_recommendations_authorizationId`, `Context__Context_recommendations`.`contextRecommendationId` AS `Context__Context_recommendations_contextRecommendationId`, `Context__Context_recommendations`.`profileId` AS `Context__Context_recommendations_profileId`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`id` AS `ccb636808c912b7629305069fc3f8c7098a495b36a1c81db8c8b2c88292c06f`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`createdDate` AS `b25a37f868987db7bd5ee9e3a85a589f24ed481ef542a85805c7f0b68bf4f31`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`updatedDate` AS `fa645b49577b7e49f536b89e2483f76e56bd96161e4571639cb11b83d1bb292`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`version` AS `8d89a8874cac95d57cb1f33efbdc40699af093ffdb42f45c1c782a2d4fb90f2`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`credentialRules` AS `122173152242f5bfd7208dfe4fde4db5794d32b1aeb2aa46067fb9f8d01b443`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`privilegeRules` AS `802adeafc30070c6fbefb52e8c209b8545087a7a9e15c4157c0a82ffa6d8438`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`verifiedCredentialRules` AS `4e37c61f9313ff2e70897581b17cc7b9d4771cb1c63d337f9b8cbc75acdec12`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`anonymousReadAccess` AS `9e3308ce00e54d7d61203719fce85ee7b74d66af83778162218471cf6e9ceb3`, `Context_authorization`.`id` AS `Context_authorization_id`, `Context_authorization`.`createdDate` AS `Context_authorization_createdDate`, `Context_authorization`.`updatedDate` AS `Context_authorization_updatedDate`, `Context_authorization`.`version` AS `Context_authorization_version`, `Context_authorization`.`credentialRules` AS `Context_authorization_credentialRules`, `Context_authorization`.`privilegeRules` AS `Context_authorization_privilegeRules`, `Context_authorization`.`verifiedCredentialRules` AS `Context_authorization_verifiedCredentialRules`, `Context_authorization`.`anonymousReadAccess` AS `Context_authorization_anonymousReadAccess` FROM `context` `Context` LEFT JOIN `reference` `Context__Context_recommendations` ON `Context__Context_recommendations`.`contextRecommendationId`=`Context`.`id`  LEFT JOIN `authorization_policy` `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea` ON `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`id`=`Context__Context_recommendations`.`authorizationId`  LEFT JOIN `authorization_policy` `Context_authorization` ON `Context_authorization`.`id`=`Context`.`authorizationId` WHERE (`Context`.`id` = '03a66953-de0a-47c4-8c29-ded61da53487')) `distinctAlias` ORDER BY `Context_id` ASC LIMIT 1"
          },
          "code": "ER_BAD_FIELD_ERROR",
          "errno": 1054,
          "sqlMessage": "Unknown column 'Context__Context_recommendations.contextRecommendationId' in 'field list'",
          "sqlState": "42S22",
          "index": 0,
          "sql": "SELECT DISTINCT `distinctAlias`.`Context_id` AS `ids_Context_id` FROM (SELECT `Context`.`id` AS `Context_id`, `Context`.`createdDate` AS `Context_createdDate`, `Context`.`updatedDate` AS `Context_updatedDate`, `Context`.`version` AS `Context_version`, `Context`.`vision` AS `Context_vision`, `Context`.`impact` AS `Context_impact`, `Context`.`who` AS `Context_who`, `Context`.`authorizationId` AS `Context_authorizationId`, `Context`.`ecosystemModelId` AS `Context_ecosystemModelId`, `Context__Context_recommendations`.`id` AS `Context__Context_recommendations_id`, `Context__Context_recommendations`.`createdDate` AS `Context__Context_recommendations_createdDate`, `Context__Context_recommendations`.`updatedDate` AS `Context__Context_recommendations_updatedDate`, `Context__Context_recommendations`.`version` AS `Context__Context_recommendations_version`, `Context__Context_recommendations`.`name` AS `Context__Context_recommendations_name`, `Context__Context_recommendations`.`uri` AS `Context__Context_recommendations_uri`, `Context__Context_recommendations`.`description` AS `Context__Context_recommendations_description`, `Context__Context_recommendations`.`authorizationId` AS `Context__Context_recommendations_authorizationId`, `Context__Context_recommendations`.`contextRecommendationId` AS `Context__Context_recommendations_contextRecommendationId`, `Context__Context_recommendations`.`profileId` AS `Context__Context_recommendations_profileId`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`id` AS `ccb636808c912b7629305069fc3f8c7098a495b36a1c81db8c8b2c88292c06f`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`createdDate` AS `b25a37f868987db7bd5ee9e3a85a589f24ed481ef542a85805c7f0b68bf4f31`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`updatedDate` AS `fa645b49577b7e49f536b89e2483f76e56bd96161e4571639cb11b83d1bb292`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`version` AS `8d89a8874cac95d57cb1f33efbdc40699af093ffdb42f45c1c782a2d4fb90f2`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`credentialRules` AS `122173152242f5bfd7208dfe4fde4db5794d32b1aeb2aa46067fb9f8d01b443`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`privilegeRules` AS `802adeafc30070c6fbefb52e8c209b8545087a7a9e15c4157c0a82ffa6d8438`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`verifiedCredentialRules` AS `4e37c61f9313ff2e70897581b17cc7b9d4771cb1c63d337f9b8cbc75acdec12`, `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`anonymousReadAccess` AS `9e3308ce00e54d7d61203719fce85ee7b74d66af83778162218471cf6e9ceb3`, `Context_authorization`.`id` AS `Context_authorization_id`, `Context_authorization`.`createdDate` AS `Context_authorization_createdDate`, `Context_authorization`.`updatedDate` AS `Context_authorization_updatedDate`, `Context_authorization`.`version` AS `Context_authorization_version`, `Context_authorization`.`credentialRules` AS `Context_authorization_credentialRules`, `Context_authorization`.`privilegeRules` AS `Context_authorization_privilegeRules`, `Context_authorization`.`verifiedCredentialRules` AS `Context_authorization_verifiedCredentialRules`, `Context_authorization`.`anonymousReadAccess` AS `Context_authorization_anonymousReadAccess` FROM `context` `Context` LEFT JOIN `reference` `Context__Context_recommendations` ON `Context__Context_recommendations`.`contextRecommendationId`=`Context`.`id`  LEFT JOIN `authorization_policy` `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea` ON `1e5e7671df59239b309509cf7a726198e9c90cecefd4cc126ed26cf099046ea`.`id`=`Context__Context_recommendations`.`authorizationId`  LEFT JOIN `authorization_policy` `Context_authorization` ON `Context_authorization`.`id`=`Context`.`authorizationId` WHERE (`Context`.`id` = '03a66953-de0a-47c4-8c29-ded61da53487')) `distinctAlias` ORDER BY `Context_id` ASC LIMIT 1",
          "stacktrace": [
            "QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'Context__Context_recommendations.contextRecommendationId' in 'field list'",
            "    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:222:33)",
            "    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)",
            "    at Query._callback (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:488:16)",
            "    at Query.Sequence.end (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)",
            "    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)",
            "    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)",
            "    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)",
            "    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)",
            "    at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)",
            "    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)",
            "    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)",
            "    at Socket.emit (node:events:527:28)",
            "    at addChunk (node:internal/streams/readable:315:12)",
            "    at readableAddChunk (node:internal/streams/readable:289:9)",
            "    at Socket.Readable.push (node:internal/streams/readable:228:10)",
            "    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
          ]
        }
      }
    }
  ],
  "data": {
    "hub": {
      "context": {
        "recommendations": null
      }
    }
  }
}
```

**Comment by valentinyanakiev** [comment]
Profile `storageBucketId` was not needed so I removed it. It is no longer breaking the migration, but there are API issues after the migration.

**Comment by hero101** [comment]
@valentinyanakiev I have not seen any API issues. Try again with the latest code and let me know if it's reproducible.

**Review by valentinyanakiev — APPROVED** [review]

**Pull request merged**
