### PR TITLE
Squash old migrations into one.

### PR DESCRIPTION
**Pull request by alstojanovic**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by techsmyth** [comment]
@alstojanovic @valentinyanakiev super to see this one coming in :) One thought though is that I would like these migrations still visible in the code base as copying from older ones is a huge timesaver, and when doing new ones then nice to be able to reference them rather than making new code / changing the head. Maybe create an "old migrations" folder?

**Comment by alstojanovic** [comment]
There was an old-migrations folder while working but decided to remove it in the end. I don't see an issue with having old migrations in a separate folder. @valentinyanakiev thoughts?

**Review by valentinyanakiev — CHANGES_REQUESTED** [review]
This doesn't work. As discussed, there are two scenarios:

1. There are no prior migrations and we have an empty `alkemio` schema. Then the new migration should create the schema.
2. There were prior migrations and. Then the new migration should NOT create the schema.

Also tests should pass.

**Review by valentinyanakiev — DISMISSED** [review]
Works now.

**Pull request closed without merging**
