### PR TITLE
added migration to update the set of types for visuals to allow usage of webp images

### PR DESCRIPTION
**Pull request by techsmyth**

### CODE REVIEW

**Review by alstojanovic — COMMENTED** [review]
I think there is a constructor for Visual that may need an update as well.

**Comment by techsmyth** [comment]
@alstojanovic yes good catch - that constructor also needs to be updated.

**Comment by techsmyth** [comment]
@alstojanovic fixed the constructor

**Review by alstojanovic — APPROVED** [review]
Tested migration and both up and down work.

**Pull request merged**
