### PR TITLE
Auth optimization

### PR DESCRIPTION
**Pull request by techsmyth**
StorageBucket + document authorization reset is done in memory, to reduce the load on the database in terms of calls.

These two auth services now do not re-load their data but check that the required fields are there when called. It is the responsibility of the calling party to save if needed. The methods are also no longer async as all updates are in-memory. 

Please see how this one performs - it should on a big space remove I think a good part of the database load...to be seen if it is material enough.

### CODE REVIEW

**Comment by valentinyanakiev** [comment]
```gql
query {
  space(ID: "building-alkemio-org") {
    id
    ...authorizationOnSpace
    subspaces {
      id
      ...authorizationOnSpace
      subspaces {
        id
        ...authorizationOnSpace
      }
    }
  }
}

fragment authorizationOnSpace on Space {
  storageAggregator {
    id
    authorization {
      id
      myPrivileges
    }
    storageAggregators {
      id
      authorization {
        id
        myPrivileges
      }
      # storageBuckets {
      #   ...authorizationOnStorageBucket
      # }
    }
    # storageBuckets {
    #   ...authorizationOnStorageBucket
    # }
    directStorageBucket {
      ...authorizationOnStorageBucket
    }
  }
  collaboration {
    id
    authorization {
      id
      myPrivileges
    }
    callouts {
      id
      authorization {
        id
        myPrivileges
      }
      comments {
        id
        authorization {
          id
          myPrivileges
        }
      }
      contributions {
        id
        authorization {
          id
          myPrivileges
        }
        link {
          id
          authorization {
            id
            myPrivileges
          }
          profile {
            id
            ...authorizationOnProfile
          }
        }
        post {
          id
          authorization {
            id
            myPrivileges
          }
          profile {
            id
            ...authorizationOnProfile
          }
        }
        whiteboard {
          id
          authorization {
            id
            myPrivileges
          }
          profile {
            ...authorizationOnProfile
          }
        }
      }
      framing {
        id
        authorization {
          id
          myPrivileges
        }
        profile {
          ...authorizationOnProfile
        }
        whiteboard {
          id
          authorization {
            id
            myPrivileges
          }
          profile {
            ...authorizationOnProfile
          }
        }
      }
    }
    timeline {
      id
      authorization {
        id
        myPrivileges
      }
      calendar {
        id
        authorization {
          id
          myPrivileges
        }
        events {
          id
          authorization {
            id
            myPrivileges
          }
        }
      }
    }
  }
}

fragment authorizationOnProfile on Profile {
  id
  authorization {
    id
    myPrivileges
  }
  references {
    id
    authorization {
      id
      myPrivileges
    }
  }
  storageBucket {
    ...authorizationOnStorageBucket
  }
  tagsets {
    id
    authorization {
      id
      myPrivileges
    }
  }
}

fragment authorizationOnStorageBucket on StorageBucket {
  id
  documents {
    id
    authorization {
      id
      myPrivileges
    }
    tagset {
      id
      authorization {
        id
        myPrivileges
      }
    }
  }
  authorization {
    id
    myPrivileges
  }
}
```
Gives me same results from develop reset auth and this branch reset auth

**Review by valentinyanakiev — DISMISSED** [review]
The code implies there is one entry point for each of the nested `applyAuthorizationPolicy` methods, which is not the case. There are various `CREATE` methods that need to apply the policies, and they do, but moving the db save outside of the encapsulated method has broken all those places. @hero101 is having a look about a tactical fix.

**Comment by techsmyth** [comment]
@valentinyanakiev I was aware that saving would then need to be done for places outside - and I thought I had done it, e.g. for callout creation etc. But maybe I missed one. Key way to track this down would be to look for applyAuthorizationPolicy inside of *.mutation.ts files - they would be the ones to look for.

**Review by hero101 — APPROVED** [review]
Has been tested locally with `callouts, upload` scripts. Merging this code and I will continue working on a more systematical and predictable approach.

**Pull request merged**
