### PR TITLE
Docker compose migration mysql:8.0.11 -> mariadb:10.7.1

### PR DESCRIPTION
**Pull request by hero101**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

> **The old volume must be deleted because the two databases differ in their engines.**

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by techsmyth — CHANGES_REQUESTED** [review]
If this is meant to be a drop in repacement then I am seeing an issue. I dropped the db in mysqlworkbench and recreated it, but then the startup of the services fails with many errors. I then wiped volumes in docker etc and it worked better but still was not starting:

image

Re wider points:
- the name of the container should no longer be "mysql"
- we still have a package called "mysql", should that not be updated?
- the various containers (kratos, rabbitmq etc) all need to work with the new one and that was not happening for me
- what about our create_db.sh file + the commands in there?
- what db mgmt tool should we use  or do we stay with mysqlworkbench?
- we also have env vars related to MYSQL e.g. in docker file etc. Keep the name or switch to calling them just "SQL"?
A good search on mysql in our repo shows up quite some usages. 

It may be that we need to schedule a lot of the above into a follow up story.

**Comment by hero101** [comment]
@techsmyth 
> If this is meant to be a drop in repacement then I am seeing an issue. I dropped the db in mysqlworkbench and recreated it, but then the startup of the services fails with many errors. I then wiped volumes in docker etc and it worked better but still was not starting

What errors? What is not starting?
image

**Comment by techsmyth** [comment]
2022-02-21 20:56:16 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728

2022-02-21 20:56:16 0 [Note] InnoDB: Completed initialization of buffer pool

2022-02-21 20:56:16 0 [ERROR] InnoDB: Invalid flags 0x4800 in ./ibdata1

2022-02-21 20:56:16 0 [ERROR] InnoDB: Plugin initialization aborted with error Data structure corruption

2022-02-21 20:56:16 0 [Note] InnoDB: Starting shutdown...

2022-02-21 20:56:17 0 [ERROR] Plugin 'InnoDB' init function returned error.

2022-02-21 20:56:17 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.

2022-02-21 20:56:17 0 [Note] Plugin 'FEEDBACK' is disabled.

2022-02-21 20:56:17 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded

2022-02-21 20:56:17 0 [Warning] 'default-authentication-plugin' is MySQL 5.6 / 5.7 compatible option. To be implemented in later versions.

2022-02-21 20:56:17 0 [ERROR] Unknown/unsupported storage engine: InnoDB

2022-02-21 20:56:17 0 [ERROR] Aborting

2022-02-21 20:57:08+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.1+maria~focal started.

2022-02-21 20:57:08+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'

2022-02-21 20:57:08+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.1+maria~focal started.

2022-02-21 20:57:08 0 [Note] mysqld (server 10.7.1-MariaDB-1:10.7.1+maria~focal) starting as process 1 ...

2022-02-21 20:57:08 0 [Note] InnoDB: Compressed tables use zlib 1.2.11

2022-02-21 20:57:08 0 [Note] InnoDB: Number of transaction pools: 1

2022-02-21 20:57:08 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions

2022-02-21 20:57:08 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)

2022-02-21 20:57:08 0 [Note] InnoDB: Using Linux native AIO

2022-02-21 20:57:08 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728

2022-02-21 20:57:08 0 [Note] InnoDB: Completed initialization of buffer pool

2022-02-21 20:57:08 0 [ERROR] InnoDB: Invalid flags 0x4800 in ./ibdata1

2022-02-21 20:57:08 0 [ERROR] InnoDB: Plugin initialization aborted with error Data structure corruption

2022-02-21 20:57:08 0 [Note] InnoDB: Starting shutdown...

2022-02-21 20:57:09 0 [ERROR] Plugin 'InnoDB' init function returned error.

2022-02-21 20:57:09 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.

2022-02-21 20:57:09 0 [Note] Plugin 'FEEDBACK' is disabled.

2022-02-21 20:57:09 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded

2022-02-21 20:57:09 0 [Warning] 'default-authentication-plugin' is MySQL 5.6 / 5.7 compatible option. To be implemented in later versions.

2022-02-21 20:57:09 0 [ERROR] Unknown/unsupported storage engine: InnoDB

2022-02-21 20:57:09 0 [ERROR] Aborting

**Comment by techsmyth** [comment]
Steps:
- wipe all existing docker containers, volumes etc
- checkout develop
- run docker-compose command to start the services
- run migration
- start the server
- stop the server
- stop the services
- checkout this branch
- start the services via docker-compose

**Comment by hero101** [comment]
> Steps:
> 
> * wipe all existing docker containers, volumes etc
> * checkout develop
> * run docker-compose command to start the services
> * run migration
> * start the server
> * stop the server
> * stop the services
> * checkout this branch
> * start the services via docker-compose

From the description: 
> The old volume must be deleted because the two databases differ in their engines

You have to delete the db volume (old - MySQL) in order for the new one (mariadb) to work.

**Review by techsmyth — APPROVED** [review]
Approved with caveat that the other issues need to be captured separately and that we update release notes with need for a full migration.

**Review by valentinyanakiev — APPROVED** [review]
Worked for me, but double-check the lifecycle issue with Evgeni. Lifecycle data is just a normal text field with a json, updating it should work normally.

**Comment by Comoque1** [comment]
The lifecycle issue with canvases is not reproducible with the latest client version (containing the latest Excalidraw package).
The following issues were experienced:
1. Integration tests related to `organization verification` are failing:
  - [ ] when set event: "MANUALLY_VERIFY" 
  - **expected:**  state: "manuallyVerified", nextEvents: "["RESET"]", 
  - **actual**: "state": "verificationPending",
        "nextEvents": [
          "MANUALLY_VERIFY",
          "REJECT"
        ]
  - [ ] when set event: "RESET" 
  - **expected:**  state: "notVerified", nextEvents: "["VERIFICATION_REQUEST"]", 
  - **actual**:` "message": "Unable to update state: provided event (RESET) not in valid set of next events: MANUALLY_VERIFY,REJECT",` 
image

2. Communications: all communications fail with the following error: `"message": "Cannot read property 'publish' of undefined",`


3. I wasn't able to make the notifications working.
The error below was thrown on notifications service, when notification must be triggered.
image
image

**Comment by valentinyanakiev** [comment]
https://github.com/alkem-io/server/pull/1782

**Pull request closed without merging**
