### PR TITLE
initial pass at removing add member privilege from space admins

### PR DESCRIPTION
**Pull request by techsmyth**
Removed privilege role on community that gave GRANT holders also the ability to ADD MEMBERS
Extended credential rule for global admins on community to also grant ADD MEMBER
Extended community policy updates on challenge / opportunity to grant the ADD MEMBER privilege to all admins 

Note: needs careful verification.

| |GA|GHA|SA|CA|OA|
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| space      | Yes       | Yes | **No** | No | No |
| challenge      | Yes       | Yes | Yes | Yes | No |
| opportunity      | Yes       | Yes | Yes | Yes | Yes |

### CODE REVIEW

**Review by hero101 — CHANGES_REQUESTED** [review]
GA, GHA fully implemented.
**SA has the privilege on Space.**
CA fully implemented.
OA fully implemented.

**Comment by techsmyth** [comment]
@hero101 will need to look later. One simple question to double check: I assume you did an authorization policy reset before testing it?

**Comment by techsmyth** [comment]
@hero101 just retested this, and a space admin that is not global admin does not have the privilege:
image

Can you please do an authorization reset and then test?

**Comment by hero101** [comment]
@techsmyth I have retested with authorization reset - Still the same results. 
Also tried with a fresh database, on a fresh Space - same results.
Let's have a call.

**Comment by Comoque1** [comment]
I have added a couple of tests to verify it and with this branch the results look like this:

Space:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1N6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5220af2736dd1351b577b348c4309cba2e929aae/image.png)

Challenge:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2F6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c31991952ecf2a62db7acb1c6be418e99ba91ae9/image.png)

Opportunity:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2V6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--36b5c3b4a57297728ed0ca2872a0c575321d4e21/image.png)

**Review by hero101 — APPROVED** [review]
Verified by QA. Covered by API tests

**Pull request merged**
