### PR TITLE
Profiles: applied to other entities

### PR DESCRIPTION
**Pull request by techsmyth**
The following entities now have profiles:
- Callout
- Canvas
- InnovationPack
- Prooject
- AspectTemplate
- LifecycleTemplate
- CanvasTemplate

The TemplateInfo is removed and replaced by Profile.
The NameableOld base entity is removed.

Migration:
- Added up / down. 

The Nameable base entity type now has a profile. 

Graphql samples updated.

To do:
- test migration on real data
- dataloaders added for new profiles

### CODE REVIEW

**Comment by Comoque1** [comment]
Error is thrown when create a hub

**Comment by techsmyth** [comment]
@Comoque1 this may be an issue with the test...can you describe the scenario? Important is to know where the test is trying to access the "tagset" field

**Comment by Comoque1** [comment]
> @Comoque1 this may be an issue with the test...can you describe the scenario? Important is to know where the test is trying to access the "tagset" field

The issue was happening as I was querying `tagset` as part of Organization data, but it is unavailable for User and Organization Profiles. Updated in the tests.

**Comment by Comoque1** [comment]
Update callout is failing:
image
image

**Comment by Comoque1** [comment]
Cannot create aspect on default callout
image

**Comment by Comoque1** [comment]
Sending message on discussion callout, throws an error
image

**Comment by Comoque1** [comment]
all server issues above are resolved

**Pull request merged**
