### PR TITLE
Notification preferences

### PR DESCRIPTION
**Pull request by valentinyanakiev**
Added the following definitions + migration:
- NOTIFICATION_COMMUNICATION_DISCUSSION_CREATED_ADMIN
- NOTIFICATION_COMMUNICATION_UPDATE_SENT_ADMIN

### CODE REVIEW

**Review by techsmyth — COMMENTED** [review]
Just ran the migration locally but I do not see the new preferences showing up in my profile:

image

**Comment by atstoyanov** [comment]
There is a filter in the UI.

**Review by techsmyth — CHANGES_REQUESTED** [review]
The migration is not actually creating the new preferences for users, only for those without any preferences. This migration needs to check if each user has the preferences being added.

**Review by techsmyth — APPROVED** [review]
Working now

**Pull request merged**
