### PR TITLE
Global roles tidy up

### PR DESCRIPTION
**Pull request by techsmyth**
Global Admin Spaces ==> Global Support
Global Admin Community ==> Global Community Reader
Space to have a new setting under privacy called "Allow Alkemio Support Admin Access";

New enum: PlatformRole
Mutations for platform roles combined into one with the role being specified. 
Mutations for organizaton roles combined into one with the role being specified. 

Migration up added

Authorization logic adjusted so that Global Support now optionally has the same privileges as space admins

Notifications are triggered for any change to a global role, or for the direct addition of any credentials (which is a global action):
image

Other changes while tidying up code:
- SaveAsTemplate now assigned to all admins
- CREATE_RELATION privilege removed

### CODE REVIEW

**Comment by Comoque1** [comment]
Global admin doesn't have rights to update space nameId
image

**Comment by techsmyth** [comment]
good catch...this one is now fixed. Good if you can make an overview of the gaps you see and send them through...

**Comment by Comoque1** [comment]
> good catch...this one is now fixed. Good if you can make an overview of the gaps you see and send them through...

Fixed!

Another 3 with same root - user cannot 
- create post on call for posts callout
- create whiteboard on whiteboard collection
- create reference on documents callout
image

**Comment by Comoque1** [comment]
Performing `ContributorsPageUsers` request fails with : ` "message": "Enum \"AuthorizationCredential\" cannot represent value: \"global-admin-community\"",`
```
query ContributorsPageUsers($first: Int!, $after: UUID, $filter: UserFilterInput) {
  usersPaginated(first: $first, after: $after, filter: $filter) {
    ...UserContributorPaginated
    __typename
  }
}

fragment UserContributorPaginated on PaginatedUsers {
  users {
    ...UserContributor
    __typename
  }
  pageInfo {
    ...PageInfo
    __typename
  }
  __typename
}

fragment UserContributor on User {
  id
  nameID
  isContactable
  agent {
    id
    credentials {
      id
      type
      resourceID
      __typename
    }
    __typename
  }
  userProfile: profile {
    id
    displayName
    location {
      city
      country
      __typename
    }
    visual(type: AVATAR) {
      ...VisualUri
      __typename
    }
    tagsets {
      ...TagsetDetails
      __typename
    }
    __typename
  }
  __typename
}

fragment VisualUri on Visual {
  id
  uri
  name
  __typename
}

fragment TagsetDetails on Tagset {
  id
  name
  tags
  allowedValues
  type
  __typename
}

fragment PageInfo on PageInfo {
  startCursor
  endCursor
  hasNextPage
  __typename
}
```
```
{
  "first": 16,
  "filter": {
    "firstName": "",
    "lastName": "",
    "email": ""
  }
}
```
image

**Comment by techsmyth** [comment]
@Comoque1 second one re global-admin-community was a bootstrap template issue. That is now fixed - so if you pull latest + reset your db you should be ok

**Comment by techsmyth** [comment]
@Comoque1 the creating post on call for posts is ok now I think - please check it out. I was seeing that I needed to refresh the page on the client to see the new post - is that known?

**Comment by Comoque1** [comment]
> @Comoque1 the creating post on call for posts is ok now I think - please check it out. I was seeing that I needed to refresh the page on the client to see the new post - is that known?

The fixes are working fine now.
Regarding the post card - not reproducible on ACC env, which means, that this is introduced with these changes (the client probably or some failed merge)

**Comment by Comoque1** [comment]
When I try to authenticate with old "SpacesAdmin" user - auth fails
image

**Comment by techsmyth** [comment]
@Comoque1 I checkout out dev on client + server, reset db, assigned a test account to global admin spaces, migrated to 2164 on both + was able to login with the global admin spaces just fine. So I cannot reproduce. Can you point me to the actual test that failed?

**Review by ccanos — DISMISSED** [review]

**Review by ccanos — DISMISSED** [review]

**Review by ccanos — APPROVED** [review]

**Comment by Comoque1** [comment]
> @Comoque1 I checkout out dev on client + server, reset db, assigned a test account to global admin spaces, migrated to 2164 on both + was able to login with the global admin spaces just fine. So I cannot reproduce. Can you point me to the actual test that failed?

I am not able to find concrete steps to reproduce the issue. I will raise a separate bug about it.

Notifications on global roles changes are not triggered.

**Pull request merged**
