### PR TITLE
Feature accounts-spaces - 2 - Accounts to have multiple spaces, all users / orgs to have exactly one account

### PR DESCRIPTION
**Pull request by techsmyth**
Account now supports having multiple level zero spaces: typeorm + logic updated

New users and organizations get an account created where they are the host

Registration module expanded to have a) creation of both new users and organizations b) to take care of auth policy resets on the associated accounts (to avoid circular dependencies)

Only level zero spaces have accountId field set, so removed usage of this field for other purposes e.g. Search.

Migration added to move all users / orgs to have exactly one Account. 

Addressed many issues with circular dependencies, resulting in new platform.hub module to allow lookup of the current InnovationHub based on url. 

Tested the following scenarios
- local db with two spaces, (and two accounts) for with same org as host. One space has a subspace
- migration combines the accounts, and ensures subspace only shows up under level zero space

### CODE REVIEW

**Comment by Comoque1** [comment]
Organization cannot be deleted:
Create Organization and Delete it:
image

**Comment by Comoque1** [comment]
Creating a space using GA throws an error:
```
mutation CreateSpace($spaceData: CreateSpaceOnAccountInput!) {
  createSpace(spaceData: $spaceData) {
    id
    __typename
  }
}
```
```
{
  "spaceData": {
    "accountID": "cf5b552e-01bf-4e52-b6b8-1b1cf3fbe045",
    "nameID": "444",
    "profileData": {
      "displayName": "4234",
      "tagline": "",
      "location": {
        "city": "",
        "country": ""
      }
    },
    "tags": []
  }
}
```

image

**Comment by Comoque1** [comment]
Above issues: fixed!
InnovationFlowTemplate on space, fails to be returned:
```
query AdminSpaceChallengesPage($spaceId: UUID_NAMEID!) {
  space(ID: $spaceId) {
    id
    subspaces {
      id
      profile {
        id
        displayName
        url
        __typename
      }
      __typename
    }
    defaults {
      id
      innovationFlowTemplate {
        id
        profile {
          ...InnovationFlowProfile
          __typename
        }
        states {
          displayName
          description
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment InnovationFlowProfile on Profile {
  id
  displayName
  description
  tagsets {
    ...TagsetDetails
    __typename
  }
  references {
    id
    name
    description
    uri
    __typename
  }
  bannerNarrow: visual(type: CARD) {
    ...VisualFull
    __typename
  }
  __typename
}

fragment TagsetDetails on Tagset {
  id
  name
  tags
  allowedValues
  type
  __typename
}

fragment VisualFull on Visual {
  id
  uri
  name
  allowedTypes
  aspectRatio
  maxHeight
  maxWidth
  minHeight
  minWidth
  alternativeText
  __typename
}
```
```
{
  "spaceId": "222"
}
```
image

**Comment by ccanos** [comment]
@Comoque1 try again please

**Comment by Comoque1** [comment]
> @Comoque1 try again please

Fixed!

**Comment by Comoque1** [comment]
Client doesn't pick user accountID on space creation.
image

**Comment by ccanos** [comment]
Yeah, Neil has told me that may be better to just remove space creation from administration but I'm trying something quick to keep it at least for now, I may have it very shortly

**Comment by Comoque1** [comment]
When update space nameID, the request: UpdateSpacePlatformSettings fails:
image

**Comment by Comoque1** [comment]
The request: AssignLicensePlanToAccount fails:
image

**Comment by Comoque1** [comment]
Space creation fails again:
image

**Comment by ccanos** [comment]
@valentinyanakiev I think a lot works but I didn't get to fix something quite annoying.
When I create a subspace, I'm getting a tagset for the innovationFlow with `tagsetTemplateId = null`, and I think they shouldn't be like that.

If I create a space, and a subspace inside I'm getting this error on the subspace page
image

`SELECT * FROM alkemio.tagset where tagsetTemplateId is null and type != 'freeform'` I think this query should return 0 results, 
image

**Pull request merged**
