### PR TITLE
url for accessing directly on profile entity

### PR DESCRIPTION
**Pull request by techsmyth**
Allowing a profile to return the URL used to access it
Allowing a storage bucket to return the parent entity key information (type, url, displayName) with which it is associated

image

The url generator service handles all the common profile types.

Todo: tests are not liking the type field on Profile...

### CODE REVIEW

**Comment by techsmyth** [comment]
@valentinyanakiev please take this one home - not been at all fun to get to this point, but it is key code that will hopefully save us a bunch of hassle moving forward. It does need some more testing, but it is pretty close I think.

**Comment by techsmyth** [comment]
@valentinyanakiev test harness errors look scary, but if you take away the last commit it comes down to one error.

**Comment by valentinyanakiev** [comment]
> @valentinyanakiev test harness errors look scary, but if you take away the last commit it comes down to one error.

There are 245 compile errors. I can't even start it.

**Comment by techsmyth** [comment]
@valentinyanakiev I tried to reproduce the error you were having but without luck. We can ignore postTemplate + whiteboardTemplate on callout as they will shortly be gone. I tried innovation pack + they were working fine. Can you please share the query you used here?

**Comment by valentinyanakiev** [comment]
> @valentinyanakiev I tried to reproduce the error you were having but without luck. We can ignore postTemplate + whiteboardTemplate on callout as they will shortly be gone. I tried innovation pack + they were working fine. Can you please share the query you used here?

```gql
query {
  space(ID:"uwv") {
    storageBucket {
			id
    }
    challenges {
      storageBucket {
        id
      ...storageBucket
      }
    }
  }
}

fragment storageBucket on StorageBucket {
      childStorage {
        parentEntity {
          type
        }
      }
}
```

You can spread the fragment anywhere where a storageBucket exists and test it easily that way

**Review by valentinyanakiev — APPROVED** [review]

**Pull request merged**
