### PR TITLE
added new field on Community to get my membership status

### PR DESCRIPTION
**Pull request by techsmyth**
To simplify the client logic related to membership status label.

### CODE REVIEW

**Review by alstojanovic — APPROVED** [review]
Havent't tested but code looks ok. Nice removal of that additional call to get the communit.

**Comment by alstojanovic** [comment]
Approved but didn't saw that this was a WIP. If there is need for additional changes please re-request review.

**Comment by techsmyth** [comment]
@alstojanovic only a draft as I was not able to run migrations and so could not test it. It is ready I think to go in once it has had some usage - I will try myself later...

**Comment by valentinyanakiev** [comment]
Let's test it on Dev, I already merged and we have too many open PRs

**Comment by valentinyanakiev** [comment]
Need to start converging if we are to release soon

**Pull request merged**
