### PR TITLE
Add default tagset to callouts.

### PR DESCRIPTION
**Pull request by alstojanovic**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by techsmyth — DISMISSED** [review]
Nice and clean; working fine for me.

**Comment by techsmyth** [comment]
@alstojanovic please also do the same for InnovationPack + Canvas

**Comment by alstojanovic** [comment]
@techsmyth please check if the CARD visual migration is ok for the InnovationPack. I also added a call to add card visual on innovation pack creation. In the down migration I am deleting the default tagsets and CARD visuals but not sure if we need/want to do it.

**Review by techsmyth — APPROVED** [review]
Works nicely. I also added in the tagsets as part of Canvas + InnovationPack creation - minor hange compared to migration but needed.

**Comment by alstojanovic** [comment]
I left it out because it was added in Carlos's PR to not have conflict maybe.

**Pull request merged**
