### PR TITLE
Rename interactions to vcInteractions in resolvers

### PR DESCRIPTION
**Pull request by valeksiev**
Needed for https://github.com/alkem-io/client-web/issues/6520

### CODE REVIEW

**Review by techsmyth — APPROVED** [review]
Made a couple of simplifications:
- did not need field decorator on interface as have a field resolver 
- retrieve the room as part of typeorm loading instead of setting explicitly (cleaner)

Only other thought is if it helps to add a field resolver for the contributor instead of just returning the UUID?

But suggest this one goes in as is if you are ok with the changes in the last two commits.

**Comment by valeksiev** [comment]
I was having trouble with the decorators/resolver functions and was not sure which one we prefer.

Re the room - didn’t like the _circular_ loading but agreed it’s cleaner. 

VC uuid works fine for now and if we want to change it I’d suggest a bigger change but it’s outside the scope of this PR for sure.

I think you can go ahead and merge it.

**Comment by techsmyth** [comment]
@valeksiev thanks for comments. Actually now this is merged I presume the client also needs merging?

**Comment by valeksiev** [comment]
I need to address some comments on the client first - either today or tomorrow.

**Comment by techsmyth** [comment]
Great, Monday of course also fine - just team needs to be aware that client is out of sync with server.

**Pull request merged**
