### PR TITLE
Ensure platform authorization is reset if not already done

### PR DESCRIPTION
**Pull request by techsmyth**
To avoid development issues...

### CODE REVIEW

**Comment by alstojanovic** [comment]
The platform authorization reset is not performed correctly. The errors in graphql requests regarding 'read' access are present.
image

Steps to reproduce:
- Reset db
- Run migrations
- start server
- Open forum page on client

**Comment by alstojanovic** [comment]
@techsmyth I guess this means the bootstrap doesn't throw errors anymore but we still need to call platform reset manually for some functionality.

**Comment by techsmyth** [comment]
@alstojanovic I see the fix - give me a few minutes - it is a trivial one...

**Review by alstojanovic — APPROVED** [review]
Platform authorization is now properly reset after bootstrap process.

**Pull request merged**
