### PR TITLE
new module to hold agent info + associated cache service (#3638)

### PR DESCRIPTION
**Pull request by valentinyanakiev**
Reverting PR as it broke state transitions.
Needs a more thorough review.

### CODE REVIEW

**Comment by Comoque1** [comment]
Update organization verification flow state fails after the first first update, with authorization error for GA:
``` 
updateState [
        {
          message: "Authorization: unable to grant 'update' privilege: event on organization verification: f74c5bcd-8d4e-4323-872c-10372e3d07b8 user: 7ed5e2b2-8426-489f-b0c4-7a9e3709b7de",
          code: 'FORBIDDEN_POLICY'
        }
      ]
```

**Comment by Comoque1** [comment]
Space member, doesn't have access to private space activity logs:
 ```
resActivity [
      {
        message: "Authorization: unable to grant 'read' privilege: Collaboration activity query: space.member@alkem.io user: 86ddaadb-d0a2-4db6-bad8-19f4db32d280",
        code: 'FORBIDDEN_POLICY'
      }
    ]
```

**Comment by Comoque1** [comment]
All tests related to updating states of lifecycle fail
```
updateState [
      {
        message: "Authorization: unable to grant 'update' privilege: event on challenge innovation flow: 5e020594-f329-4a92-a16f-99ec273a6720 user: 7ed5e2b2-8426-489f-b0c4-7a9e3709b7de",
        code: 'FORBIDDEN_POLICY'
      }
    ]

```

**Comment by Comoque1** [comment]
Space member, who creates challenge, doesn't have rights to create opportunity
```
resAssignMember [
      {
        message: "Authorization: unable to grant 'create-opportunity' privilege: opportunityCreate: chal-texti user: 86ddaadb-d0a2-4db6-bad8-19f4db32d280",
        code: 'FORBIDDEN_POLICY'
      }
    ]
```

**Comment by Comoque1** [comment]
User who joined community (space and challenge), doesn't have "READ" privileges to community:
image

**Comment by techsmyth** [comment]
@valentinyanakiev @Comoque1 I am taking this update into the licensing branch; working a bunch with agents there. Leave branch up for now but will not be taken forward.

**Pull request closed without merging**
