### PR TITLE
Feature Account-spaces

### PR DESCRIPTION
**Pull request by techsmyth**
Library+ defaults
===========
Level zero spaces now have a library and defaults; all subspaces access these entities through fields that redirect via the levelZeroSpaceID .

Migration also moves the storage aggregator to be that of the Space.

Account with multiple spaces
===================
Account now supports having multiple level zero spaces: typeorm + logic updated

New users and organizations get an account created where they are the host

Registration module expanded to have a) creation of both new users and organizations b) to take care of auth policy resets on the associated accounts (to avoid circular dependencies)

Only level zero spaces have accountId field set, so removed usage of this field for other purposes e.g. Search.

Migration added to move all users / orgs to have exactly one Account. 

Addressed many issues with circular dependencies, resulting in new platform.hub module to allow lookup of the current InnovationHub based on url.

### CODE REVIEW

**Comment by Comoque1** [comment]
Migration fails on clean DB:
image

**Comment by Comoque1** [comment]
The query:
```
query{
  users{
    id
    account{
      id
    }
  }
}
```
fails with error: `"message": "Cannot return null for non-nullable field User.account.",`
image

**Comment by Comoque1** [comment]
Newly registered users generate profiles with empty credential rules:
Register new user and perform the following query:
```
query {
  user(ID:"ev.dimitrovv@gmail.com") {
    id
    profile{
      displayName
    }
  }
}
```
Error: `"message": "AuthorizationPolicy without credential rules provided: 1385eb65-033a-4965-9237-445882b62eb1",`

image

**Comment by techsmyth** [comment]
> Newly registered users generate profiles with empty credential rules: Register new user and perform the following query:
> 
> ```
> query {
>   user(ID:"ev.dimitrovv@gmail.com") {
>     id
>     profile{
>       displayName
>     }
>   }
> }
> ```
> 
> Error: `"message": "AuthorizationPolicy without credential rules provided: 1385eb65-033a-4965-9237-445882b62eb1",`
> 
> image

@Comoque1 @ccanos This one should now be fixed, there was a double assignment of a credential for registered users. 

The other issue whereby user.account.id looks to me to be bad data...

**Comment by techsmyth** [comment]
@Comoque1 re the error you found above re user accounts, what data set were you using for this? It might be that there is a scenario in the migration that has been missed

**Comment by Comoque1** [comment]
> @Comoque1 re the error you found above re user accounts, what data set were you using for this? It might be that there is a scenario in the migration that has been missed

@techsmyth I was using clean DB
The above issues now seem to be resolved.

**Comment by Comoque1** [comment]
Another one:
Subspace.account fails:
Create Space and a Subspace and query the account under the subspace
```query {
  lookup {
    space(ID: "c8b1906c-9d3a-4448-8fef-2dbb28bcf8e7") {
      account {
        id
      }
    }
  }
}
```

**Comment by Comoque1** [comment]
When trying to create L2 subspace, request fails:
image

**Comment by Comoque1** [comment]
Space member has ["CONTRIBUTE", "FILE_UPLOAD", "READ"] to private subspace
Create private space with private subspace
Assign member to the space
Navigate to the subspace with it - he could see everything
image

**Comment by Comoque1** [comment]
VC campaign user doesn't have rights to create innovation pack:
image

**Comment by Comoque1** [comment]
Registered Users don't have access to spaces page 'http://localhost:3000/spaces'
image

**Comment by techsmyth** [comment]
> VC campaign user doesn't have rights to create innovation pack: image

At the moment that is correct, need to refine the logic re what privileges the user gets. The button to create one should be conditional on having the right privileges.

**Comment by techsmyth** [comment]
> Registered Users don't have access to spaces page 'http://localhost:3000/spaces' image

@ccanos this is a bug I have introduced. I added in a privilege check on the space.settings field, but that should be removed.

**Comment by techsmyth** [comment]
> FILE_UPLOAD

@Comoque1 regarding the private space + extra privileges, can you please share a screen shot of the authorization policy for that space? Maybe use the nice page that is there on the client :) I am half expected to see a rule called platformReadContributeRegistered there...

**Comment by Comoque1** [comment]
> > FILE_UPLOAD
> 
> @Comoque1 regarding the private space + extra privileges, can you please share a screen shot of the authorization policy for that space? Maybe use the nice page that is there on the client :) I am half expected to see a rule called platformReadContributeRegistered there...

@techsmyth having the following setup:
Private Space with Private L1 Subspace
The Subspace settings are as follows:
``` 
privacy: { mode: SpacePrivacyMode.Private },
    collaboration: {
      allowMembersToCreateCallouts: false,
      allowMembersToCreateSubspaces: false,
      inheritMembershipRights: false,
    },
```
Space Member has (originally, space member should not have access to these resources)
image

**Comment by techsmyth** [comment]
@Comoque1 merged from develop with authorization policy update in there, and fixed one issue related to private subpace - can you please check again?

**Comment by techsmyth** [comment]
> > Registered Users don't have access to spaces page 'http://localhost:3000/spaces' image
> 
> @ccanos this is a bug I have introduced. I added in a privilege check on the space.settings field, but that should be removed.

@Comoque1 this is also fixed I think

**Comment by Comoque1** [comment]
Api tests updated.
Now they are passing with latest changes.

**Review by ccanos — APPROVED** [review]

**Pull request merged**
