### PR TITLE
initial pass at private subspaces

### PR DESCRIPTION
**Pull request by techsmyth**
The whole private subspaces code had been lost. Added it back in + made simpler...

### CODE REVIEW

**Comment by techsmyth** [comment]
@Comoque1 @valentinyanakiev please try it out, changes are straightforward enough but I have not had time to do more than verify a private challenge is not accessible to space member (i.e. no READ privilege)

**Comment by Comoque1** [comment]
The issue seems to be partially fixed. Now space admin, don't have any rights to private challenge:

**Comment by techsmyth** [comment]
Yes likely there is an additional rile needed to grant admins of parent space(s) rights

**Comment by techsmyth** [comment]
@Comoque1 just pushed the rule to extend right for space admin to private subspace, please have a look. If it is fixed then please merge this PR - we then build on top of this one.

**Comment by Comoque1** [comment]
Now the documents tests pass, so will merge this PR (the issue was caught when running it).
Additional testing will be required on different subspace properties.

**Review by Comoque1 — APPROVED** [review]

**Pull request merged**
