### PR TITLE
cascading of removals, especially re authorization

### PR DESCRIPTION
**Pull request by techsmyth**
Moved all base entity types into one folder
Moved all functionality related to manipulating authorizationDefinitions to a service in that entity's folder
Moved the relationship between organisation / challenge and organisation / ecoverse to be based on credentials - so no longer direct references. 

Database schema is reset for hopefully the last time...

Note: still some entities being left over but should be a lot less...

### CODE REVIEW

**Comment by Comoque1** [comment]
With these changes, there is significant improvements in terms of less data leftovers.
There is an issue introduced:
querying user from through application, throws an error: `"message": "Cannot return null for non-nullable field Application.user."`
image
The user exists.

**Comment by techsmyth** [comment]
> With these changes, there is significant improvements in terms of less data leftovers.
> There is an issue introduced:
> querying user from through application, throws an error: `"message": "Cannot return null for non-nullable field Application.user."`
> image
> The user exists.

Hi Evgeni, afraid needed to go deep on the code again with circular dependencies. Issue with user application field should now be fixed.

**Comment by Comoque1** [comment]
Unable to delete Organisation after the latest  changes
image
image

**Comment by Comoque1** [comment]
Tests passing
image

**Review by Comoque1 — APPROVED** [review]

**Pull request merged**
