### PR TITLE
Data integrity schema migration

### PR DESCRIPTION
**Pull request by hero101**
- Added missing indecies
- Changed some idecies to be unique, in order to enforce one-to-one relationship\
- Added missing foreign keys where applicable
- Added foreign keys for `createdBy` where applicable. Decorators added to enforce one-to-one on `createdBy`
## Things to verify
- does `createdBy` resolves to `User` instead of `string` as it's defined. That would mean further code changes.
- platform is parent of library, communication, storage_agg
- library is parent of storage_agg
- callout_framing is parent of whiteboard, whiteboardrt
- innovation_pack is parent of profile, template_set
- createdBy now have foreign keys in ~10+/- entities
- all createdBy must be set to `ON DELETE SET NULL`

### CODE REVIEW

**Comment by techsmyth** [comment]
@hero101 super deep PR. One other angle that comes to mind is if there are circular dependencies introduced by having so many entities now refer to User entity - good to check that also. Otherwise happy to discuss Monday some of the open points that should be verified. 

This one potentially can also have an impact on performance I assume given so many indexes / relationships are added? For good or bad?

**Comment by hero101** [comment]
Found a problem while creating Space.
image

**Comment by hero101** [comment]
Bear in mind that some statements will be obsolete when we migrate the whiteboards

**Comment by valentinyanakiev** [comment]
query failed: ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)
error: Error: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'
    at Packet.asError (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'",
  sql: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)'
}
Migration "addConstraints1705843901852" failed, error: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'
query: ROLLBACK
Error during migration run:
QueryFailedError: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'
    at Query.onResult (/home/valentin/work/repos/alkemio/server/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.execute (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  query: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)',
  parameters: undefined,
  driverError: Error: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'
      at Packet.asError (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    sqlMessage: "Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'",
    sql: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)'
  },
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'",
  sql: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)'

**Comment by valentinyanakiev** [comment]
> query failed: ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`) error: Error: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157' at Packet.asError (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packets/packet.js:728:17) at Query.execute (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/commands/command.js:29:26) at PoolConnection.handlePacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:456:32) at PacketParser.onPacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:85:12) at PacketParser.executeStart (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packet_parser.js:75:16) at Socket. (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:92:25) at Socket.emit (node:events:527:28) at Socket.emit (node:domain:475:12) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) { code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', sqlMessage: "Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'", sql: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)' } Migration "addConstraints1705843901852" failed, error: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157' query: ROLLBACK Error during migration run: QueryFailedError: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157' at Query.onResult (/home/valentin/work/repos/alkemio/server/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:222:33) at Query.execute (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/commands/command.js:36:14) at PoolConnection.handlePacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:456:32) at PacketParser.onPacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:85:12) at PacketParser.executeStart (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packet_parser.js:75:16) at Socket. (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:92:25) at Socket.emit (node:events:527:28) at Socket.emit (node:domain:475:12) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) { query: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)', parameters: undefined, driverError: Error: Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157' at Packet.asError (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packets/packet.js:728:17) at Query.execute (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/commands/command.js:29:26) at PoolConnection.handlePacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:456:32) at PacketParser.onPacket (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:85:12) at PacketParser.executeStart (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/packet_parser.js:75:16) at Socket. (/home/valentin/work/repos/alkemio/server/node_modules/mysql2/lib/connection.js:92:25) at Socket.emit (node:events:527:28) at Socket.emit (node:domain:475:12) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) { code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', sqlMessage: "Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'", sql: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)' }, code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', sqlMessage: "Duplicate entry 'd60251be-a2b7-437b-a3ac-6dfea72a1584' for key 'opportunity.IDX_a37ebd95962285f8339bffb157'", sql: 'ALTER TABLE `opportunity` ADD UNIQUE INDEX `IDX_a37ebd95962285f8339bffb157` (`innovationFlowId`)'

Started digging, the index is fine, the data is not... Tracked in https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/3641

**Comment by valentinyanakiev** [comment]
I have looked at the code, tested it, made some changes, and have the following observations + suggestions:
- Most of the FK relationships, unique keys are OK
- Platform is parent of library, communication, storage aggregator - OK
- library is parent of storage_agg - OK
- callout_framing is parent of whiteboard, whiteboardrt - OK (merged after the other set of changes)
- innovation_pack is parent of profile, template_set - OK

Now, CreatedBy + InvitedUser etc - I suggest we take separately. I tested it, and there are multiple issues:
- CreatedBy is set out as 1:1 and implies uniqueness in the both tables, e.g. I create a document, then CreatedBy in document is unique. But I can create many documents. This should be 1:many
- We can't really use string, it needs to be User. Otherwise the decorator doesn't match the definition and it quickly becomes a mess of loading / not loading / undefined etc, not handled by our code
- Changing to User implies going through every place these are used and loading them, as it would be a reference
- Applications, Invitations should also have User instead of string for the id
Added https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/3642 for tracking this, will need to take it separately (it's not a blocker for finding the orphan data issues)

**Review by valentinyanakiev — APPROVED** [review]

**Pull request merged**
